apiVersion: v1
data:
  controller_manager_config.yaml: "apiVersion: controller-runtime.sigs.k8s.io/v1alpha1\n\
    kind: ControllerManagerConfig\nhealth:\n  healthProbeBindAddress: :8081\nmetrics:\n\
    \  bindAddress: 127.0.0.1:8080\nwebhook:\n  port: 9443\nleaderElection:\n  leaderElect:\
    \ true\n  resourceName: 095fd8bb.kvdi.io\n"
kind: ConfigMap
metadata:
  name: {{ include "kvdi.fullname" . }}-manager-config
  labels:
    {{- include "kvdi.labels" . | nindent 4 }}
