apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kvdi.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "kvdi.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kvdi.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kvdi.serviceAccountName" . }}
