apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.3.6
    created: "2021-10-24T17:30:15.584500716+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 26ff5c00728881bd9ee516195b9d61925682a182d794b8a527ede3766c626e8a
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.6.tgz
    version: v0.3.6
  - apiVersion: v2
    appVersion: v0.3.5
    created: "2021-10-24T17:30:15.581488394+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: eebe58c68188c8601df6196bb8d13fc4ae5f8651532861aa7f52b77d99564f02
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.5.tgz
    version: v0.3.5
  - apiVersion: v2
    appVersion: v0.3.4
    created: "2021-10-24T17:30:15.579723685+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: e8bc3549a7500a83ebdc35ef5be48110d1b57c571de56a49973f468ab582f2eb
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.4.tgz
    version: v0.3.4
  - apiVersion: v2
    appVersion: v0.3.3
    created: "2021-10-24T17:30:15.577824977+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4fd46beddf26228ace1aa30d1f9e7a84bcf27ed2a4809799ba0ea160dfd44784
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.3.tgz
    version: v0.3.3
  - apiVersion: v2
    appVersion: v0.3.2
    created: "2021-10-24T17:30:15.575874739+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 23b99a9cc5281541edf5c402555fb5a85c1812d1fac9d864cda9628a72953b21
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.2.tgz
    version: v0.3.2
  - apiVersion: v2
    appVersion: v0.3.1
    created: "2021-10-24T17:30:15.573877215+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 118ce0338cc036de90c81a01572a91f622093b131321c3f75e92b24d8aeed164
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.1.tgz
    version: v0.3.1
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2021-10-24T17:30:15.570701485+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4b0620db91f21777ab9389574e95aa4a3ab812be7382727ddd94c7e81a3e7de7
    name: kvdi
    type: application
    urls:
    - kvdi-v0.3.0.tgz
    version: v0.3.0
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2021-10-24T17:30:15.569022343+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 426e46b70297154030266abf2d832838c0d00c58a0b3390e78281400cea961fa
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.2.tgz
    version: v0.2.2
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2021-10-24T17:30:15.567447678+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 29af60d73698d30af6253b7d8317904a66f4de6378a16ac287d3c5905035be65
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.1.tgz
    version: v0.2.1
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2021-10-24T17:30:15.565594299+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: f50123e34bc62e2954da3ff2ae747f7d82c250cef5c53cf25d9dd163b542ef77
    name: kvdi
    type: application
    urls:
    - kvdi-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v2
    appVersion: v0.1.4
    created: "2021-10-24T17:30:15.563743644+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4dd6ffd2bb17689d042782056e7f90bb8bb1ad403a9dc4a9de340329f4d70322
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.4.tgz
    version: v0.1.4
  - apiVersion: v2
    appVersion: v0.1.3
    created: "2021-10-24T17:30:15.560226682+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: f2b9302e26762c49ed0ad53835b2c190e6c7d0722c8497f46f1c2080fd5b0576
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.3.tgz
    version: v0.1.3
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2021-10-24T17:30:15.559050708+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 369e83caa627379ba04bf79471da18e0ebca85ec527fc13729eb7bb733f502ef
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.2.tgz
    version: v0.1.2
  - apiVersion: v2
    appVersion: v0.1.1
    created: "2021-10-24T17:30:15.557307926+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13667a42c4be002e2980ca0625bb4a7399b171ee73a1f0fe1a3c4de7bdc377ba
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.1.tgz
    version: v0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-10-24T17:30:15.556106624+03:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 75b553c4fea1303767743944a8e470f6d56784b85f8a0698edc5e786fc3c05ac
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.0.tgz
    version: v0.1.0
generated: "2021-10-24T17:30:15.55417498+03:00"
